# Chargers configs
[chargers]

[chargers.tier_1]
# The amount of energy the charger can hold
# Range: 0 ~ 9223372036854775807
storage = 25000
# The amount of energy/tick that can be inserted
# Range: 0 ~ 9223372036854775807
max_input = 500
# The amount of energy/tick that can be extracted
# This is the max speed items would be charged at, actual speed could be slower depending on item
# Range: 0 ~ 9223372036854775807
max_output = 500

[chargers.tier_2]
# The amount of energy the charger can hold
# Range: 0 ~ 9223372036854775807
storage = 500000
# The amount of energy/tick that can be inserted
# Range: 0 ~ 9223372036854775807
max_input = 10000
# The amount of energy/tick that can be extracted
# This is the max speed items would be charged at, actual speed could be slower depending on item
# Range: 0 ~ 9223372036854775807
max_output = 10000

[chargers.tier_3]
# The amount of energy the charger can hold
# Range: 0 ~ 9223372036854775807
storage = 1000000
# The amount of energy/tick that can be inserted
# Range: 0 ~ 9223372036854775807
max_input = 25000
# The amount of energy/tick that can be extracted
# This is the max speed items would be charged at, actual speed could be slower depending on item
# Range: 0 ~ 9223372036854775807
max_output = 25000

[chargers.tier_4]
# The amount of energy the charger can hold
# Range: 0 ~ 9223372036854775807
storage = 4197997269003186
# The amount of energy/tick that can be inserted
# Range: 0 ~ 9223372036854775807
max_input = 9223372036854775807
# The amount of energy/tick that can be extracted
# This is the max speed items would be charged at, actual speed could be slower depending on item
# Range: 0 ~ 9223372036854775807
max_output = 9223372036854775807

[chargers.wireless]
# The amount of energy the wireless charger can hold
# Range: 0 ~ 9223372036854775807
storage = 200000
# The amount of energy/tick that can be inserted
# Range: 0 ~ 9223372036854775807
max_input = 8000
# The amount of energy/tick that can be extracted
# This is the max speed items would be charged at, actual speed could be slower depending on item
# Range: 0 ~ 9223372036854775807
max_output = 8000
# The range from the charger that item will be charged
# Range: 0 ~ 128
range = 24
