#General settings
[General]
#When enabled the loot coupon can double boss loot
doubleBossLoot = false
#A list of entities that can't have loot doubled [Syntax: 'minecraft:bat']
entityBlacklist = [""]

#Wandering Trader Trades
[Trades]
#Defines whether or not the Brewing Coupon is obtainable from the Wandering Trader
enableBrewingCoupon = true
#Defines whether or not the Crafting Coupon is obtainable from the Wandering Trader
enableCraftingCoupon = true
#Defines whether or not the Experience Coupon is obtainable from the Wandering Trader
enableExperienceCoupon = true
#Defines whether or not the Furnace Coupon is obtainable from the Wandering Trader
enableFurnaceCoupon = true
#Defines whether or not the Loot Coupon is obtainable from the Wandering Trader
enableLootCoupon = true
#Defines whether or not the Trading Coupon is obtainable from the Wandering Trader
enableTradingCoupon = true
