# Changed WoolyCow SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Wooly cow SpawnRate" = 0
# Changed Umbra Cow SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Umbra Cow SpawnRate" = 0
# Changed Teacup Pig SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
" Teacup Pig SpawnRate" = 0
# Changed Cluckshroom SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Cluckshroom SpawnRate" = 0
# Changed Fancy Chicken SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Fancy Chicken SpawnRate" = 0
# Changed Duck SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Duck SpawnRate" = 0
# Changed Jolly LLama SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Jolly Llama SpawnRate" = 0
# Changed Horned Sheep SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Horned Sheep SpawnRate" = 0
# Changed Hyper Rabbit SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Hyper Rabbit SpawnRate" = 0
# Changed Moobloom SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Moobloom SpawnRate" = 0
# Changed Moolip SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Moolip SpawnRate" = 0
# Changed Jumbo Rabbit SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Jumbo Rabbit SpawnRate" = 0
# Changed Bone Spider SpawnRate. [0 ~ 1000]
# Range: 0 ~ 1000
"Bone Spider SpawnRate" = 0
# Changed Stray Bone Spider SpawnRate. [0 ~ 1000]
# Range: 0 ~ 1000
"Stray Bone Spider SpawnRate" = 0
# Changed BoulderingZombie SpawnRate. [0 ~ 1000]
# Range: 0 ~ 1000
"BoulderingZombie SpawnRate" = 0
# Changed LobberZombie SpawnRate. [0 ~ 1000]
# Range: 0 ~ 1000
"LobberZombie SpawnRate" = 0
# Changed TropicalSlime SpawnRate. [0 ~ 1000]
# Range: 0 ~ 1000
"TropicalSlime SpawnRate" = 0
# Changed SkeletonWolf SpawnRate In Overworld. [0 ~ 1000]
# Range: 0 ~ 1000
"SkeletonWolf SpawnRate In Overworld" = 0
# Changed SkeletonWolf SpawnRate In Nether. [0 ~ 1000]
# Range: 0 ~ 1000
"SkeletonWolf SpawnRate In Nether" = 0
# Changed WitherSkeletonWolf SpawnRate In Nether. [0 ~ 1000]
# Range: 0 ~ 1000
"WitherSkeletonWolf SpawnRate In Nether" = 0
# Changed Baby Ghast SpawnRate In Nether. [0 ~ 1000]
# Range: 0 ~ 100
"Baby Ghast SpawnRate In Nether" = 0
# Changed Magma Cow SpawnRate In Nether. [0 ~ 1000]
# Range: 0 ~ 100
"Magma Cow SpawnRate In Nether" = 0
# Changed Mud Spawn in Overworld.
"Mud Spawn in Overworld" = false
# Changed Common Cow SpawnRate. [0 ~ 100]
# Range: 0 ~ 100
"Common Cow SpawnRate" = 2
