# Mod settings
[veincreeper]
#	  (id,colour,displayName,dropsExp,isDestructive,radius, doesFire). id must be unique. There are two recipe types you will want to add after adding new creepers: 'veincreeper:explosion' recipes to make creeper explosions convert ore, and 'veincreeper:trap' recipes to convert mobs into other mobs on the trap block, so add these to your modpack/datapack/scripts based on how all vanilla ores are set up by default https://github.com/Lothrazar/VeinCreeper/tree/trunk/1.20/src/main/resources/data/veincreeper/recipes . Yes each creeper have multiple recipes of each type .  The 'id' string must exactly match the "veincreeer" property used in the explosion recipe, this will link the creeper mob to the ore explosion recipe.  Colour values are used as an overlay to existing creeper texture.
creepers = [
  "coal_creeper,#281414,Coal,true,false,2.2,false",
  "iron_creeper,#823C14,Iron,true,false,2.2,false",
  "diamond_creeper,#39ADFA,Diamond,true,false,2.2,false",
  "copper_creeper,#f06d02,Copper,true,false,2.3,false",
  "gold_creeper,#F0F000,Gold,true,false,2.5,false",
  "redstone_creeper,#EB2300,Redstone,false,false,2.5,false",
  "lapis_creeper,#0000FF,Lapis,true,false,2.5,false",
  "emerald_creeper,#00FF00,Emerald,false,false,2.6,false",
  "quartz_creeper,#C7C5C5,Quartz,true,true,2.5,false",
  "purple_creeper,#FF00FF,Purple,true,false,3.0,false",
  "stone_creeper,#696969,Stone,true,false,1.9,false",
  "netherite_creeper,#2F4F4F,Netherite,true,true,2.9,true",
  "zinc_creeper,#add9b4,Zinc,true,false,10,false"
]
#   Register spawn eggs items. false here will remove the eggs.  If you added new mobs to the config you will also need to make a resource pack to setup your new eggs with one file per egg from assets/veincreeper/models/item/spawn_egg_[id] in your modpack's resource-pack.  Find the eggs in the creative tab
spawn_eggs = true
